##
## EPITECH PROJECT, 2021
## makefile
## File description:
## makefile
##

NAME = solver

SRC = *.c

all:
	gcc -g3 -o $(NAME) $(SRC)

clean:
	rm -f *~ | rm -f *.o

fclean: clean
	rm -f $(NAME)

re:	fclean all
